main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
    path('', views.index, name="index")
]

stopover/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/models.py
from django.db import models


class Search (models.Model):
    search = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.search

    class Meta:
        verbose_name_plural = "Searches"

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Search

def index(request):
    if request.method == 'GET':
        return render(request, 'base.html')

    if request.method == 'POST':
        search = request.POST.get('search')
        print(search)
        Search.objects.create(search=search)
        return render(request,'base.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StopOVer</title>
</head>
<body>
<header>
    <a href="#">StopOver</a>
    <form action="{% url 'main:index' %}" method="POST">
        {% csrf_token %}
        <input type="text" id="search" name="search" placeholder="Find your ideal Festival Experience" required>
       <button id="search-button">Search</button>
    </form>
</header>

</center>
</body>
</html>